services:
  # 1) CRUD API (Node + Express)
  - type: web
    name: weather-crud
    env: node
    plan: free
    rootDir: crud
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        sync: false

  # 2) Fetcher (Cron Job → เรียก crud API)
  - type: cron
    name: weather-fetcher
    env: node
    plan: free
    schedule: "*/30 * * * *" # ทุก 30 นาที
    rootDir: fetcher
    buildCommand: npm install
    startCommand: node index.js

  # 3) Display UI (Frontend)
  - type: web
    name: weather-display
    env: node
    plan: free
    rootDir: display
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: API_BASE_URL
        value: https://weather-crud.onrender.com
